# working directory: ./financetracker/backend
FROM postgres:16.0

# override the configuration file for max connections, etc.
COPY ./db/pg_config/postgresql.conf /etc/postgresql.conf
COPY ./db/pg_config/pg_hba.conf /etc/pg_hba.conf

EXPOSE 5432