# working directory: ./financetracker/backend
FROM postgres:latest

# override the configuration file for max connections, etc.
COPY ./db/pg_config/postgresql.conf /var/lib/postgresql/data/postgresql.conf
COPY ./db/pg_config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf

EXPOSE 5432