"""20240830_205906

Revision ID: 0a65599dd83f
Revises: ddeb6da829a0
Create Date: 2024-08-30 20:59:07.852118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a65599dd83f'
down_revision: Union[str, None] = 'ddeb6da829a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('supports_transactions', sa.Boolean(), nullable=True))
    op.add_column('institution', sa.Column('supports_auth', sa.Boolean(), nullable=True))
    op.add_column('institution', sa.Column('url', sa.Text(), nullable=True))
    op.drop_column('institution', 'products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('products', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('institution', 'url')
    op.drop_column('institution', 'supports_auth')
    op.drop_column('institution', 'supports_transactions')
    # ### end Alembic commands ###
