"""20240901_170320

Revision ID: 0ed2dbec1b7f
Revises: 4021a763bcaa
Create Date: 2024-09-01 17:03:21.483426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed2dbec1b7f'
down_revision: Union[str, None] = '4021a763bcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('supports_investments', sa.Boolean(), nullable=True))
    op.drop_column('institution', 'supports_institutions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('supports_institutions', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('institution', 'supports_investments')
    # ### end Alembic commands ###
