"""20240914_144033

Revision ID: 227fe3f12d61
Revises: 
Create Date: 2024-09-14 14:40:35.681749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227fe3f12d61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'supports_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('supports_accounts', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
