"""20240823_013521

Revision ID: 35966d9bdd7e
Revises: c4011a33155d
Create Date: 2024-08-23 01:35:24.030091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35966d9bdd7e'
down_revision: Union[str, None] = 'c4011a33155d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'balance_available',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    op.alter_column('account', 'balance_current',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    op.alter_column('account', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    op.alter_column('account', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'account_type',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('account', 'account_name',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('account', 'balance_current',
               existing_type=sa.LargeBinary(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('account', 'balance_available',
               existing_type=sa.LargeBinary(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
