"""20240901_163306

Revision ID: 4021a763bcaa
Revises: f497deb6ec2e
Create Date: 2024-09-01 16:33:07.939088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4021a763bcaa'
down_revision: Union[str, None] = 'f497deb6ec2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('supports_institutions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'supports_institutions')
    # ### end Alembic commands ###
