"""20240818_210849

Revision ID: 425b07aad74d
Revises: 822647634538
Create Date: 2024-08-18 21:08:50.095380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425b07aad74d'
down_revision: Union[str, None] = '822647634538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('transaction', sa.Column('is_pending', sa.Boolean(), nullable=True))
    op.drop_column('transaction', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'is_pending')
    op.drop_column('transaction', 'name')
    # ### end Alembic commands ###
