"""20240828_193349

Revision ID: 59363ce7ec02
Revises: caae942ac395
Create Date: 2024-08-28 19:33:51.532577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59363ce7ec02'
down_revision: Union[str, None] = 'caae942ac395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_key', 'access_key_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('financetracker_user', 'access_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financetracker_user', sa.Column('access_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('access_key', 'access_key_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
