"""20240806_030304

Revision ID: 611767e03d39
Revises: eb24f68907ff
Create Date: 2024-08-06 03:03:05.288186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611767e03d39'
down_revision: Union[str, None] = 'eb24f68907ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financetracker_user', 'transactions_sync_cursor',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financetracker_user', 'transactions_sync_cursor',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
