"""20240901_175857

Revision ID: 6c03130cb310
Revises: 
Create Date: 2024-09-01 17:58:58.353049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c03130cb310'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_holding', sa.Column('cost_basis', sa.LargeBinary(), nullable=True))
    op.add_column('investment_holding', sa.Column('institution_price', sa.Float(), nullable=True))
    op.add_column('investment_holding', sa.Column('institution_price_as_of', sa.DateTime(), nullable=True))
    op.add_column('investment_holding', sa.Column('institution_value', sa.Float(), nullable=True))
    op.add_column('investment_holding', sa.Column('unofficial_currency_code', sa.String(length=20), nullable=True))
    op.add_column('investment_holding', sa.Column('vested_quantity', sa.LargeBinary(), nullable=True))
    op.add_column('investment_holding', sa.Column('vested_value', sa.LargeBinary(), nullable=True))
    op.drop_column('investment_holding', 'type')
    op.drop_column('investment_holding', 'subtype')
    op.drop_column('investment_holding', 'amount')
    op.drop_column('investment_holding', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_holding', sa.Column('date', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('investment_holding', sa.Column('amount', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('investment_holding', sa.Column('subtype', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('investment_holding', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('investment_holding', 'vested_value')
    op.drop_column('investment_holding', 'vested_quantity')
    op.drop_column('investment_holding', 'unofficial_currency_code')
    op.drop_column('investment_holding', 'institution_value')
    op.drop_column('investment_holding', 'institution_price_as_of')
    op.drop_column('investment_holding', 'institution_price')
    op.drop_column('investment_holding', 'cost_basis')
    # ### end Alembic commands ###
