"""20240830_222140

Revision ID: 81fa85319003
Revises: 5d94aed7e144
Create Date: 2024-08-30 22:21:41.671655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fa85319003'
down_revision: Union[str, None] = '5d94aed7e144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('institution_id', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'account', 'institution', ['institution_id'], ['institution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'institution_id')
    # ### end Alembic commands ###
