"""20240818_210109

Revision ID: 822647634538
Revises: 
Create Date: 2024-08-18 21:01:10.520856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822647634538'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financetracker_user', sa.Column('last_transactions_account_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financetracker_user', 'last_transactions_account_sync')
    # ### end Alembic commands ###
