"""revision

Revision ID: 8326ae8cfeeb
Revises: 372ffd0e2163
Create Date: 2024-12-26 16:55:50.568168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8326ae8cfeeb'
down_revision: Union[str, None] = '372ffd0e2163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security', 'institution_security_id',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security', 'institution_security_id',
               existing_type=sa.String(length=80),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
