"""20240830_211838

Revision ID: 91753fa94c70
Revises: f5b6f1597f2d
Create Date: 2024-08-30 21:18:39.373370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91753fa94c70'
down_revision: Union[str, None] = 'f5b6f1597f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('access_key_institution_id_fkey', 'access_key', type_='foreignkey')
    op.drop_column('access_key', 'institution_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_key', sa.Column('institution_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_foreign_key('access_key_institution_id_fkey', 'access_key', 'institution', ['institution_id'], ['institution_id'])
    # ### end Alembic commands ###
