"""20240810_004041

Revision ID: abf007868c7a
Revises: 368b3c2f2153
Create Date: 2024-08-10 00:40:42.273133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf007868c7a'
down_revision: Union[str, None] = '368b3c2f2153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_session',
    sa.Column('auth_session_token_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['financetracker_user.user_id'], ),
    sa.PrimaryKeyConstraint('auth_session_token_id')
    )
    op.add_column('financetracker_user', sa.Column('user_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financetracker_user', 'user_type')
    op.drop_table('auth_session')
    # ### end Alembic commands ###
