"""20240826_224840

Revision ID: caae942ac395
Revises: 
Create Date: 2024-08-26 22:48:41.751399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caae942ac395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('institution_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_table('access_key',
    sa.Column('access_key_id', sa.String(length=20), nullable=False),
    sa.Column('access_key', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['financetracker_user.user_id'], ),
    sa.PrimaryKeyConstraint('access_key_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_key')
    op.drop_table('institution')
    # ### end Alembic commands ###
