"""20240901_160746

Revision ID: f497deb6ec2e
Revises: 1d2f8814ab4f
Create Date: 2024-09-01 16:07:47.862908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f497deb6ec2e'
down_revision: Union[str, None] = '1d2f8814ab4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_key', sa.Column('transactions_sync_cursor', sa.String(length=255), nullable=True))
    op.add_column('access_key', sa.Column('last_transactions_account_sync', sa.DateTime(), nullable=True))
    op.drop_column('financetracker_user', 'last_transactions_account_sync')
    op.drop_column('financetracker_user', 'transactions_sync_cursor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financetracker_user', sa.Column('transactions_sync_cursor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('financetracker_user', sa.Column('last_transactions_account_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('access_key', 'last_transactions_account_sync')
    op.drop_column('access_key', 'transactions_sync_cursor')
    # ### end Alembic commands ###
