"""20240830_211445

Revision ID: f5b6f1597f2d
Revises: 0a65599dd83f
Create Date: 2024-08-30 21:14:46.682742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b6f1597f2d'
down_revision: Union[str, None] = '0a65599dd83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_key', sa.Column('institution_id', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'access_key', 'institution', ['institution_id'], ['institution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_key', type_='foreignkey')
    op.drop_column('access_key', 'institution_id')
    # ### end Alembic commands ###
