# CONTEXT REQUIRED: financetracker/backend/
FROM python:3.11-alpine

WORKDIR /app

COPY ./api ./api
COPY ./db ./db
COPY ../.env .

RUN pip install -r ./api/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api.api:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]