on:
  push:
    branches:
      - main
      - dockerize_everything

jobs:
  unittests:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check AWS Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2